server.port: 8183
management.endpoints.web.exposure.include: "*"
spring.datasource.url: jdbc:h2:mem:upgradedb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: upgrade
spring.datasource.password: upgrade
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.h2.console.enabled: true